import type { Metadata } from "next"
import './globals.css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang = "en" className="bg-black [color-scheme:dark]">
            <body className = "bg-gradient-to-br from-gray-900 to-black text-white overscroll-none overflow-x-hidden">
                {children}
            </body>

        </html>
    )
}